server:
  port: 3000
  apiKeyHeader: x-api-key

proxy:
  enabled: true
  upstreamUrl: http://sample-api:8000
  upstreamTimeoutMs: 2500

cache:
  l1:
    maxItems: 1000
    routeTtlSeconds: 300
    apiKeyTtlSeconds: 30
    tenantPlanTtlSeconds: 60
    blacklistTtlSeconds: 15
    configTtlSeconds: 300
  l2:
    apiKeyTtlSeconds: 30
    tenantPlanTtlSeconds: 60

protectedRoutes:
  - id: graphql
    method: POST
    pathPrefix: /graphql
    upstreamPath: /graphql
    planGroup: graphql
  - id: tickets
    method: GET
    pathPrefix: /tickets
    upstreamPath: /tickets
    planGroup: graphql

plans:
  free:
    displayName: Demo Free
    shardCount: 1
    groups:
      graphql:
        limit: 6
        unit: minute
  starter:
    displayName: Demo Starter
    shardCount: 3
    groups:
      graphql:
        limit: 20
        unit: minute

blacklist:
  staticApiKeyHashes:
    - 6a2dbb79944a67e8f6fe7ea3e96f6c9af8f43d897780d589740d925668aa3c83

